permalink: /:month-:day-:year/:title.html

markdown: kramdown

# Theme settings
theme:

  # Site name
  site_name: coregroup sas

  # Google analytics UID
  google_analytics_uid: UA-2753aaaa

  # Disqus shortname, for comments
  disqus_shortname: stephan83

  # Number of featured posts on homepage
  homepage_featured: 1

  # Number of posts on homepage (in addition to featured posts)
  homepage_posts: 2

  # Number of words to display in post summaries
  featured_wordcount: 20